AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  NextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: next.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /Next/{test}/foo
            Method: GET
  FooFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: foo.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /Foo/{bar}/baz
            Method: GET
  BarFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bar.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /bar/{baz}
            Method: POST

